### ISSUE TITLE
Error after entering the command npm run build

### ISSUE THREAD

**Issue by white124bk** [okhiroyuki/redmobile-modules-generator#5]
npm run build                                                                                                           > @0.2.0 build /root/xxx/redmobile-modules-generator
> node main.js                                             
(node:25424) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir 'node_modules'
    at Object.rmdirSync (fs.js:684:3)                          at cleanDir (/root/xxx/redmobile-modules-generator/main.js:34:12)                                                     at /root/xxx/redmobile-modules-generator/main.js:60:5      at Object.<anonymous> (/root/xxx/redmobile-modules-generator/main.js:70:3)                                            at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)                                                              at Function.Module._load (internal/modules/cjs/loader.js:585:3)                                                       at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)                                                (node:25424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by okhiroyuki** [comment]
@white124bk 
What version of Node.js are you using?

**Comment by okhiroyuki** [comment]
@white124bk 
I have modified the code.
Please try to use the latest.
